# Generated by Django 3.2.2 on 2021-05-08 21:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210508_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event',
            new_name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 21, 33, 23, 635624, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='host_name',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='long_description',
            field=models.TextField(default='long description'),
        ),
        migrations.AddField(
            model_name='event',
            name='short_description',
            field=models.TextField(default='short description'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 21, 33, 23, 635624, tzinfo=utc)),
        ),
    ]
