# Generated by Django 3.2.2 on 2021-05-08 22:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210508_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 22, 55, 33, 122748, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 22, 55, 33, 122748, tzinfo=utc)),
        ),
    ]
